BEM-exercise
Stevenkwizera06/BEM-medical-core pull request #1
Opened 2022-10-21 16:33 UTC by Stevenkwizera06

###What does this PR do?
shows the medical core landing page

###Description of Task to be completed?
- The css should  include Blocks with Elements / children and also Modifiers (should  use BEM naming convention )
-  The css to use is vanilla css not any other css framework

###How should this be manually tested?
- Clone the repo
- checkout to branch ft-Dev

2022-10-24 16:31 UTC, Morrism1 requested changes
Good job! But there is some things to include. Try to use meaningful and semantic names for your BEM classes.

2022-10-24 16:31 UTC, Morrism1 commented on index.css
> +  .footer__btn-Subscribe {
This class name includes an uppercase character. BEM class names should be lowercase.

2022-10-24 16:31 UTC, Morrism1 commented on index.css
> +   /* .button--big {
Remove comments codes if they are not used.

2022-10-24 16:31 UTC, Morrism1 commented on index.html
> +                <a href="#" class="header-link-element">Home</a>
Please, Don't create new Blocks because this class here looks like a new while it could be a simple block__element like `header__link` because `header-link-element` reads like a new block also it is not a semantic name.

2022-10-24 16:31 UTC, Morrism1 commented on index.html
> +            <a href="#" class="header-link-element header-link--color">Login</a>
here you are using `header-link--color` modifier for a block `header-link` but it is not defined anywhere here.

2022-10-24 16:31 UTC, Morrism1 commented on index.html
> +        <div class="welcome__btns">
`welcome__btns` is positioned outside the Block `welcome`. Here, also there is no block  `welocme` defined above

2022-10-24 16:31 UTC, Morrism1 commented on index.html
> +            <button class="welcome__btns--big">Join us</button>
Same here!

2022-10-24 16:31 UTC, Morrism1 commented on index.html
> +            <button class="welcome__btns--size">Learn more</button>
Also here!

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.html
> +            <button class="welcome__btns--size">Learn more</button>
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.html
> +            <button class="welcome__btns--big">Join us</button>
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.html
> +        <div class="welcome__btns">
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.html
> +            <a href="#" class="header-link-element header-link--color">Login</a>
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.html
> +                <a href="#" class="header-link-element">Home</a>
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.css
> +   /* .button--big {
corrected

2022-10-25 03:18 UTC, Stevenkwizera06 commented on index.css
> +  .footer__btn-Subscribe {
corrected

2022-10-25 08:01 UTC, Morrism1 requested changes
Check everything well before submitting again.

2022-10-25 08:01 UTC, Morrism1 commented on index.html
> +            <a href="#" class="header__link-element header--color">Login</a>
`header--color` you are using a block modifier without its default block `header`

2022-10-25 08:01 UTC, Morrism1 commented on index.html
> +            <button class="welcome-section--big">Join us</button>
We talked about not using modifiers alone

2022-10-25 08:01 UTC, Morrism1 commented on index.html
> +            <button class="welcome-section--size">Learn more</button>
Samething here.

2022-10-25 12:05 UTC, Morrism1 approved these changes
🚀🚀

2022-11-01 15:30 UTC, merged